UncleGoogle/galaxy-integration-humblebundle

requirements/app.txt
requirements/dev.txt
src/library.py
src/model/game.py
src/plugin.py

- do not raise exception on single game parse error ( like in #31 )
- new sentry project id

Ignore unexpected parse errors

---

.travis.yml
README.md
requirements-dev.txt
requirements.txt
requirements/app.txt
src/manifest.json
tasks.py

Adjust code to FriendsOfGalaxy structure + get galaxy.plugin.api from pypi

---

src/library.py
src/plugin.py
tests/conftest.py

Fix refreshing for new games (orders and trove) + async shutdown

---

src/library.py
src/manifest.json
src/webservice.py

fixes #57 
HumbleBundle changed their web behavior

fix had_trove_subscription

---

.github/ISSUE_TEMPLATE/bug_report.md
src/keysgui.py
src/plugin.py

Fix for showing keys (on "install")

---

src/consts.py
src/library.py
src/plugin.py
tests/common/test_library.py
tests/conftest.py

Handle failed orders

---

.gitignore
.vscode/launch.json
.vscode/settings.json
pytest.ini
src/config.ini
src/consts.py
src/library.py
src/local/baseappfinder.py
src/local/localgame.py
src/local/macappfinder.py
src/local/pathfinder.py
src/local/winappfinder.py
src/model/game.py
src/plugin.py
src/settings.py
test.py
tests/common/test_appfinder.py
tests/common/test_downloader.py
tests/common/test_pathfinder.py
tests/common/test_plugin.py
tests/conftest.py
tests/windows/test_winappfinder.py

Support for installed games on macOS

---

src/local/pathfinder.py
tasks.py
tests/common/utils/test_decorators.py

Fix bug when checking for install games

Fix IndexError on checking installed

---

src/settings.py

when whitespaces are in user's path

Fix opening config file when whitespaces in path

---

README.md
requirements.txt
src/CHANGELOG.md
src/config.ini
src/consts.py
src/gui/options.py
src/library.py
src/model/game.py
src/plugin.py
src/webservice.py
tests/common/test_library.py
tests/common/test_plugin.py
tests/common/test_subscriptions.py
tests/conftest.py

Use newly released Galaxy feature for subscripitons
todo:

Trove as subscription

---

src/library.py

Fix not showing choice games after unlock

---

src/consts.py
src/humbledownloader.py
src/library.py
src/local/__init__.py
src/local/baseappfinder.py
src/local/localgame.py
src/local/pathfinder.py
src/model/game.py
src/model/platform.py
src/model/subscription.py
src/model/types.py
src/plugin.py
src/settings.py
src/webservice.py
tests/common/model/test_game.py
tests/common/test_pathfinder.py
tests/common/test_plugin.py
tests/common/test_subscription_games.py
tests/common/test_subscriptions.py
tests/conftest.py

Humble Choice months as separate Subscriptions

---

src/CHANGELOG.md
src/consts.py
src/gui/keys.py
src/gui/options.py
src/humbledownloader.py
src/model/game.py
src/model/product.py
src/model/subscription.py
src/plugin.py
src/settings.py
src/webservice.py
tasks.py
tests/common/test_plugin.py
tests/common/test_subscription_games.py

Subscription games refactor & cache

---

src/model/subscription.py
src/model/types.py
src/plugin.py
src/webservice.py
tests/common/test_subscriptions.py

Fix for handling Lite subscription plan

---

README.md
src/CHANGELOG.md

Release Notes for 0.8.0

---

src/local/reg_watcher.py
src/local/winappfinder.py
tests/windows/test_reg_watcher.py

Fix issue with parsing uninstall string if not-game uninstaller is used

---

src/plugin.py
tests/common/test_plugin.py

Full OSCompatibility for keys

---

src/CHANGELOG.md
src/local/__init__.py
src/local/baseappfinder.py
src/local/localgame.py
src/local/pathfinder.py
src/local/winappfinder.py
src/plugin.py
tests/common/test_appfinder.py
tests/common/test_localgame.py
tests/common/test_plugin.py

Implement get_local_size

---

src/model/subscription.py

Fix showing subscriptions

---

src/CHANGELOG.md
src/model/subscription.py
src/webservice.py

Fixes #139 
In short: adjusting to changes JSON value in humble API response. I don't know why they change key name. Maybe I need more investigation for this "initial-classic" thing.

Fix subscriptions again

---

src/plugin.py
src/webservice.py
tests/common/test_subscriptions.py

Fix to show choices before paused months

---

src/CHANGELOG.md
src/plugin.py
src/webservice.py

Fix offline plugin + Handle parse errors better for future

---

src/CHANGELOG.md
src/plugin.py
tests/common/test_opening_options.py

Related to #151 
This is to make some kind of notification for people that ever had subscription to reconnect their plugin.

Show tip to disconnect plugin for affected people

---

src/model/subscription.py
src/plugin.py
src/webservice.py
tests/common/test_subscriptions.py
tests/conftest.py

also - do not use changed marketing data
Fixes #161

Fix subscriptions - adapt to humble change & code simplification

---

galaxy_emulator.py
src/model/subscription.py
src/plugin.py
src/webservice.py
tests/common/test_api.py
tests/common/test_subscription_games.py

Fixes #165 #167 (I hope - tested on my account with quite fresh sub only so far)

Fix subscriptions and adjust to new Choice subscription shape

---

src/CHANGELOG.md
src/humbleapp/humbleapp.py
src/local/humbleapp_adapter.py
tests/humbleapp/test_humbleapp.py

fix(humbleapp): parsing not fullly initialized games in config
